language: python

python:
    - '3.6'

services:
  - xvfb

before_install:
  - sudo apt-get install gfortran
  - pip install coverage==4.5.4 # Temp fix
  - pip install coveralls
  - pip install python-coveralls
  - pip install h5py

install:
  - git clone https://github.com/sibirrer/fastell4py.git
  - cd fastell4py
  - pip install .
  - cd ..
  - git clone https://github.com/jiwoncpark/baobab.git
  - cd baobab
  - pip install -e . -r requirements.txt
  - cd ..
  - pip install .

before_script:
  - "export DISPLAY=:99.0"
  - sleep 3

script:
  - cd test
  - coverage run --source ovejero -m unittest -v *_tests.py

after_success:
  - coveralls